# FOR WINDOWS
name: epictope
channels:
  - bioconda
  - conda-forge
dependencies:
  - dssp>=4.0.0
  - r-base>=4.2.2
  - r-stringi>=1.1.7
  - r-openssl>=2.0.6
  - r-remotes>=2.4.0
  - r-curl 
  - r-rvest 
  - r-httr
  - "r-r.utils"
  - r-biocmanager
  - git
